//
//  MovieDetailsModels.swift
//  movieDB
//
//  Created by Santo Michael Sihombing on 13/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

struct genre: Decodable {
    var id: Int
    var name: String
}

struct MovieDetails: Decodable {
    
    var movieId: Int
    var movieOverview: String
    var movieImageUrl: String
    var movieTitle: String
    var adult: Bool
    var backdrop: String
    var genres: [genre]
    var voteAverage: Double
    
    enum CodingKeys: String, CodingKey {
        case movieTitle    = "title"
        case movieOverview = "overview"
        case movieImageUrl = "poster_path"
        case movieId = "id"
        case voteAverage = "vote_average"
        case adult = "adult"
        case backdrop = "backdrop_path"
        case genres = "genres"
    }
}



struct movieVideoResponse: Codable {
    let id: Int
    let results: [MovieVideo]
}

struct MovieVideo: Codable {
    let iso639_1, iso3166_1, name, key: String
    let site: String
    let size: Int
    let type: String
    let official: Bool
    let publishedAt, id: String

    enum CodingKeys: String, CodingKey {
        case iso639_1 = "iso_639_1"
        case iso3166_1 = "iso_3166_1"
        case name, key, site, size, type, official
        case publishedAt = "published_at"
        case id
    }
}
